wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/addCols                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/ameme                   
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/autoDtd                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/autoSql                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/autoXml                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/ave                     
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/aveCols                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/axtChain                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/axtSort                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/axtSwap                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/axtToMaf                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/axtToPsl                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedClip                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedCommonRegions        
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedCoverage             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedExtendRanges         
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedGeneParts            
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedGraphPack            
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedGraphToBigWig        
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedIntersect            
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedItemOverlapCount     
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedPileUps              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedRemoveOverlap        
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedRestrictToPositions  
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedSort                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedToBigBed             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedToExons              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedToGenePred           
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedToPsl                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedWeedOverlapping      
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bigBedInfo              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bigBedNamedItems        
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bigBedSummary           
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bigBedToBed             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bigPslToPsl             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bigWigAverageOverBed    
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bigWigCat               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bigWigCluster           
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bigWigCorrelate         
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bigWigInfo              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bigWigMerge             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bigWigSummary           
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bigWigToBedGraph        
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bigWigToWig             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/blastToPsl              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/blastXmlToPsl           
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/blat/                   
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/calc                    
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/catDir                  
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/catUncomment            
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/chainAntiRepeat         
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/chainFilter             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/chainMergeSort          
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/chainNet                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/chainPreNet             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/chainSort               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/chainSplit              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/chainStitchId           
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/chainSwap               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/chainToAxt              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/chainToPsl              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/chainToPslBasic         
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/checkAgpAndFa           
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/checkCoverageGaps       
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/checkHgFindSpec         
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/checkTableCoords        
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/chopFaLines             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/chromGraphFromBin       
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/chromGraphToBin         
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/colTransform            
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/countChars              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/crTreeIndexBed          
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/crTreeSearchBed         
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/dbSnoop                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/dbTrash                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/estOrient               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faAlign                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faCmp                   
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faCount                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faFilter                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faFilterN               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faFrag                  
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faNoise                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faOneRecord             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faPolyASizes            
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faRandomize             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faRc                    
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faSize                  
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faSomeRecords           
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faSplit                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faToFastq               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faToTab                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faToTwoBit              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faTrans                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/fastqStatsAndSubsample  
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/fastqToFa               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/featureBits             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/fetchChromSizes         
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/findMotif               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/gapToLift               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/genePredCheck           
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/genePredFilter          
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/genePredHisto           
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/genePredSingleCover     
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/genePredToBed           
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/genePredToBigGenePred   
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/genePredToFakePsl       
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/genePredToGtf           
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/genePredToMafFrames     
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/genePredToProt          
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/getRna                  
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/getRnaPred              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/gff3ToGenePred          
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/gff3ToPsl               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/gmtime                  
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/gtfToGenePred           
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/headRest                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/hgFindSpec              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/hgGcPercent             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/hgLoadBed               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/hgLoadChain             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/hgLoadMaf               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/hgLoadMafSummary        
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/hgLoadNet               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/hgLoadOut               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/hgLoadOutJoined         
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/hgLoadWiggle            
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/hgSpeciesRna            
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/hgTrackDb               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/hgWiggle                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/hgsql                   
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/hgsqldump               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/htmlCheck               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/hubCheck                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/hubPublicCheck          
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/ixIxx                   
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/lavToAxt                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/lavToPsl                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/ldHgGene                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/liftOver                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/liftOverMerge           
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/liftUp                  
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/linesToRa               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/localtime               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mafAddIRows             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mafAddQRows             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mafCoverage             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mafFetch                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mafFilter               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mafFrag                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mafFrags                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mafGene                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mafMeFirst              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mafOrder                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mafRanges               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mafSpeciesList          
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mafSpeciesSubset        
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mafSplit                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mafSplitPos             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mafToAxt                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mafToPsl                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mafToSnpBed             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mafsInRegion            
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/makeTableList           
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/maskOutFa               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mktime                  
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/mrnaToGene              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/netChainSubset          
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/netClass                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/netFilter               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/netSplit                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/netSyntenic             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/netToAxt                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/netToBed                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/newProg                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/newPythonProg           
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/nibFrag                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/nibSize                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/oligoMatch              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/overlapSelect           
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/paraFetch               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/paraSync                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/positionalTblCheck      
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslCDnaFilter           
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslCat                  
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslCheck                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslDropOverlap          
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslFilter               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslHisto                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslLiftSubrangeBlat     
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslMap                  
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslMrnaCover            
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslPairs                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslPartition            
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslPosTarget            
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslPretty               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslRecalcMatch          
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslReps                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslScore                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslSelect               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslSort                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslStats                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslSwap                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslToBed                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslToBigPsl             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslToChain              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslToPslx               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/pslxToFa                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/qaToQac                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/qacAgpLift              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/qacToQa                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/qacToWig                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/raSqlQuery              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/raToLines               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/raToTab                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/randomLines             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/rmFaDups                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/rowsToCols              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/sizeof                  
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/spacedToTab             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/splitFile               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/splitFileByColumn       
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/sqlToXml                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/stringify               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/subChar                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/subColumn               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/tailLines               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/tdbQuery                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/textHistogram           
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/tickToDate              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/toLower                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/toUpper                 
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/transMapPslToGenePred   
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/trfBig                  
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/twoBitDup               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/twoBitInfo              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/twoBitMask              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/twoBitToFa              
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/udr                     
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/validateFiles           
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/validateManifest        
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/wigCorrelate            
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/wigEncode               
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/wigToBigWig             
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/wordLine                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/xmlCat                  
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/xmlToSql                
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/
